$(function(){
    $('.cont1').find('.project').mouseover(function(){
        //console.log('sss');
        $('.cont1').find('.c_circle1').addClass('act');
    });
    $('.cont1').find('.project').mouseout(function(){
        //console.log('s2s');
        $('.cont1').find('.c_circle1.act').removeClass('act');
    });
    /*-----------------------------------------------------------------*/ 
    $('.cont2').find('.project').mouseover(function(){
        //console.log('sss');
        $('.cont2').find('.c_circle2').addClass('act');
    });
    $('.cont2').find('.project').mouseout(function(){
        //console.log('s2s');
        $('.cont2').find('.c_circle2.act').removeClass('act');
    });
    /*-----------------------------------------------------------------*/ 
    $('.cont3').find('.project').mouseover(function(){
        //console.log('sss');
        $('.cont3').find('.c_circle3').addClass('act');
    });
    $('.cont3').find('.project').mouseout(function(){
        //console.log('s2s');
        $('.cont3').find('.c_circle3.act').removeClass('act');
    });
    /*-----------------------------------------------------------------*/ 
    $('.cont4').find('.project').mouseover(function(){
        //console.log('sss');
        $('.cont4').find('.c_circle4').addClass('act');
    });
    $('.cont4').find('.project').mouseout(function(){
        //console.log('s2s');
        $('.cont4').find('.c_circle4.act').removeClass('act');
    });
    /*-----------------------------------------------------------------*/ 
    $('.cont5').find('.project').mouseover(function(){
        //console.log('sss');
        $('.cont5').find('.c_circle5').addClass('act');
    });
    $('.cont5').find('.project').mouseout(function(){
        //console.log('s2s');
        $('.cont5').find('.c_circle5.act').removeClass('act');
    });
    /*-----------------------------------------------------------------*/ 
    $('.cont6').find('.project').mouseover(function(){
        console.log('sss');
        $('.cont6').find('.c_circle6').addClass('act');
    });
    $('.cont6').find('.project').mouseout(function(){
        console.log('s2s');
        $('.cont6').find('.c_circle6.act').removeClass('act');
    });
});